### ISSUE TITLE
Syntax highlighting for selectors with variables in multiline text does not work

### ISSUE THREAD

**Issue by marcselman** [macabeus/vscode-fluent#19]
See the image below for an example:

![image](https://user-images.githubusercontent.com/514683/130964731-befb26e5-99c1-4a7f-84a0-d556de1474ed.png)

**Comment by macabeus** [comment]
Fix published at the version `1.0.0` 🚀 

<img width="345" alt="image" src="https://user-images.githubusercontent.com/9501115/180621333-a757aba3-7688-4f46-9c63-09488db743cc.png">
