### ISSUE TITLE
The author of this repo is too beautiful. I hate it

### ISSUE THREAD

**Issue by mikaelsouza** [macabeus/vscode-fluent#28]
Please, fix it.

**Comment by anabastos** [comment]
+1

**Comment by douglastofoli** [comment]
Obviously this is a problem that none pull request resolves.

**Comment by Cyytrus** [comment]
@douglastofoli But there's an enormous problem. Too much perfection could distract the repository readers, and the code errors would pass unnoticed.

**Comment by mikaelsouza** [comment]
So, any development on this issue?
