### ISSUE TITLE
Certain cases of multiline text do not get parsed properly.

### ISSUE THREAD

**Issue by elenakrittik** [macabeus/vscode-fluent#31]
```ftl
registration_title = Registration
registration_description_1 = You don't have a playable character yet. Let's create one!
    Answer the questions that come up.

    **What's your favorite playstyle?**

registration_choose_an_answer = Choose an answer
```
![изображение](https://github.com/macabeus/vscode-fluent/assets/77104725/b5d0dc49-b391-4184-99bd-92399ff139ee)

The problem arised from the usage of `*` at the start of a non-first line of a multiline string. If i place a `*` at the beginning of `Answer ...` the error moves there, and if i remove all `*` from the start the error disappears.

EDIT: I see you're using the official library for parsing. May this be a bug in there?

**Comment by macabeus** [comment]
> EDIT: I see you're using the official library for parsing. May this be a bug in there?

Yeah. It seems to be a bug there. You can reproduce it running on [Fluent Playground](https://projectfluent.org/play/?id=74f1ef82da0a06bf7493a58d8cad53ae).
<img width="500" alt="image" src="https://github.com/macabeus/vscode-fluent/assets/9501115/42edfd12-387f-4569-9fdf-72c4186a5eec">

Please, file an issue on [`fluent.js` repository](https://github.com/projectfluent/fluent.js).

**Comment by elenakrittik** [comment]
https://github.com/projectfluent/fluent.js/issues/620

**Comment by macabeus** [comment]
Closed because it seems to not be a bug
https://github.com/projectfluent/fluent.js/issues/620#issuecomment-1701110138
